# Generated by Django 4.1.4 on 2023-08-25 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_app", "0005_remove_user_is_email_varivied"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_email_varivied",
            field=models.BooleanField(default=False),
        ),
    ]
