# Generated by Django 4.1.4 on 2023-08-25 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("task_app", "0006_user_is_email_varivied"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
