# Generated by Django 4.1.4 on 2023-08-25 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("task_app", "0008_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
